import Head from "next/head.js";
import Header from "../components/Header";
import Hero from "../components/Hero";

// import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className="bg-[rgb(36,36,36)] text-white h-screen snap-y snap-mandatory overflow-scroll z-0">
      <Head>
        <title>Roy Ali Hasan | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />
        {/* Hero Panel  */}
        <section id="hero" className="snap-center">
          <Hero />
        </section>
      </main>
    </div>
  );
}
